// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "lucapapa-20190104043001-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://lucapapa-20190104043001-hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
